import Pkg
Pkg.add("Parameters")
Pkg.add("LinearAlgebra")
Pkg.add("Distributions")
Pkg.add("DataFrames")
Pkg.add("Random")
Pkg.add("CSV")
Pkg.add("Plots")
Pkg.add("StatsPlots")
Pkg.add("ThreadsX")
Pkg.add("ForwardDiff")
Pkg.add("Optim")
Pkg.add("PrettyTables")
Pkg.add("RCall")
Pkg.add("NLsolve")
Pkg.add("NLSolversBase")
Pkg.add("Revise")
Pkg.add("LaTeXStrings")
Pkg.add("Test")
Pkg.add("JLD2")
# Pkg.add("ProgressMeter")
Pkg.add("Glob")
Pkg.add("DataFramesMeta")
Pkg.add("Roots")
Pkg.add("Statistics")
